# LS-Tris Development Compose file

name: ls-tris-dev-compose

services:

  # Update this to the name of the service you want to work with in your docker-compose.yml file
  workspace:
    container_name: ls-tris-DevEnv
    profiles: [dev] # This service will be started only in these profiles
    # Uncomment if you want to override the service's Dockerfile to one in the .devcontainer 
    # folder. Note that the path of the Dockerfile and context is relative to the *primary* 
    # docker-compose.yml file (the first in the devcontainer.json "dockerComposeFile"
    # array). The sample below assumes your primary file is in the root of your project.
    #
    build:
      context: .
      dockerfile: Dockerfile

    # List of the ports to be forwarded from the container (necessary if not using the "host" network)
    ports: # Maps <hostPort>:<containerPort>
      - ${DEV_BACKEND_PORT:-55511}:5050 # Port used to access backend app (development mode). Default: 55511
      - ${DEV_FRONTEND_PORT:-55512}:4200 # Port used to access frontend app (development mode). Default: 55512
      - ${DEV_KARMA_PORT:-55513}:9876 # Port used to access frontend Karma's tests report (development mode). Default: 55513
      - ${DEV_BRIDGE_HTTP_PORT:-55514}:3001 # Port used to access bridge app with HTTP (development mode). Default: 55514
      - ${DEV_BRIDGE_WS_PORT:-55515}:3002 # Port used to access bridge app with WebSocket (development mode). Default: 55515

    environment: # Defines the environment variables
      BRIDGE_ADDRESS: ${BRIDGE_ADDRESS:-localhost} # The address from the user browser
      BRIDGE_HTTP_PORT: ${DEV_BRIDGE_HTTP_PORT:-55514} # The port from the user browser
      BRIDGE_WS_PORT: ${DEV_BRIDGE_WS_PORT:-55515} # The port from the user browser
      TCP_BACKEND_ADDRESS: ${TCP_BACKEND_ADDRESS:-localhost} # The address inside the docker network
      TCP_BACKEND_PORT: 5050 # The port inside the docker network

    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - ..:/workspaces/LS-Tris:cached

    networks:
      - backend-network
      - frontend-network

    # Uncomment the next four lines if you will use a ptrace-based debugger like C++, Go, and Rust.
    # cap_add:
    #   - SYS_PTRACE
    # security_opt:
    #   - seccomp:unconfined

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity